import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { microab, microABListener, type MicroabResponse } from "../../SDK/src/index";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function getServerSideProps() {
  // Lógica para buscar dados do servidor

  const appMicro = await microab();

  return {
    props: appMicro
  };
}

export default function Home( props: MicroabResponse ) {

  const { generatedJWT, sessionid } = props;

  useEffect(() => {
    // Must use useEffect to run on client side an only after component is mounted
    if (!generatedJWT || !sessionid) return;
    microABListener(sessionid, generatedJWT);
  }, [generatedJWT, sessionid]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            <li>
              Get started by editing <code>src/pages/index.tsx</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>

          <div className={styles.ctas}>
            <a href="#" rel="noopener noreferrer" className={`${styles.secondary} handleEvent`}>
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a href="#" rel="noopener noreferrer">
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a href="#" rel="noopener noreferrer">
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a href="#" rel="noopener noreferrer">
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
    </>
  );
}